### ISSUE TITLE
Elena Shushakova

### ISSUE THREAD

**Issue by AlexanderMcQueent** [SajjadPourali/Surnames#2]

**Comment by SajjadPourali** [comment]
This repository only focuses on surnames that "[Shushakova](https://github.com/SajjadPourali/Surnames/search?q=Shushakova)" is available on it.
https://github.com/SajjadPourali/Surnames/blob/407dd1d7fefc5a8e6e636981c7ba0183eca5ba61/withoutStatistics/kz.txt#L2746
https://github.com/SajjadPourali/Surnames/blob/407dd1d7fefc5a8e6e636981c7ba0183eca5ba61/withoutStatistics/ua.txt#L19732
